"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const content = {
  EN: {
    title: "Terms of Use",
    updated: "Last updated: July 1, 2025",
    back: "Back",
    sections: [
      {
        heading: "1. Nature of the Service",
        body: "Mystic Tarot is an entertainment and personal inspiration application. Readings generated by artificial intelligence are fictional and do not constitute professional advice of any kind (medical, legal, financial, psychological or spiritual). The user accepts that the service is offered for leisure purposes only.",
      },
      {
        heading: "2. Acceptance of Terms",
        body: "Accessing and using Mystic Tarot implies full acceptance of these Terms of Use. If you disagree with any of the conditions set out here, please do not use the service.",
      },
      {
        heading: "3. Free Access and Paid Credits",
        bullets: [
          { text: "The service offers 3 free readings per day, automatically renewed every 24 hours." },
          { text: "Users may purchase additional credit packs via payment through Stripe." },
          { text: "Purchased credits are stored locally in the user's browser. They are non-refundable once granted." },
          { text: "Credits do not expire as long as the user retains their browser data." },
        ],
      },
      {
        heading: "4. Payments and Billing",
        body: "Payments are processed securely by Stripe, Inc. Mystic Tarot does not store credit card data. Prices shown include applicable taxes. In the event of a dispute over a charge, the user must contact support before initiating a chargeback with their bank.",
      },
      {
        heading: "5. Acceptable Use",
        intro: "The user agrees not to:",
        bullets: [
          { text: "Attempt to manipulate the credit system or circumvent the payment system." },
          { text: "Use the service for illegal purposes or in ways that could harm third parties." },
          { text: "Reverse-engineer the system." },
        ],
      },
      {
        heading: "6. Service Availability",
        body: "Mystic Tarot is provided 'as is' and does not guarantee uninterrupted availability. The service depends on third-party APIs (Groq, Stripe, Vercel) whose availability is outside the owner's control.",
      },
      {
        heading: "7. Limitation of Liability",
        body: "The owner of Mystic Tarot shall not be liable for any direct, indirect, incidental or consequential damages arising from the use or inability to use the service. Readings generated are the product of an artificial intelligence system and should not be taken as truth or as guidance for important decisions.",
      },
      {
        heading: "8. Modifications",
        body: "The owner reserves the right to modify these terms at any time. Changes will be effective from their publication on this page. Continued use of the service after such changes implies their acceptance.",
      },
      {
        heading: "9. Applicable Law",
        body: "These terms are governed by Spanish and European Union law. For any dispute, the parties submit to the competent courts and tribunals in accordance with applicable regulations.",
      },
    ],
    footerLinks: [{ label: "Privacy Policy", href: "/privacy" }, { label: "🔮 Mystic Tarot", href: "/" }],
  },
  ES: {
    title: "Términos de Uso",
    updated: "Última actualización: 1 de julio de 2025",
    back: "Volver",
    sections: [
      {
        heading: "1. Naturaleza del servicio",
        body: "Mystic Tarot es una aplicación de entretenimiento e inspiración personal. Las lecturas generadas por inteligencia artificial son ficticias y no constituyen consejo profesional de ningún tipo (médico, legal, financiero, psicológico ni espiritual). El usuario acepta que el servicio se ofrece únicamente con fines de ocio.",
      },
      {
        heading: "2. Aceptación de los términos",
        body: "El acceso y uso de Mystic Tarot implica la aceptación plena de estos Términos de Uso. Si no estás de acuerdo con alguna de las condiciones aquí establecidas, te rogamos que no utilices el servicio.",
      },
      {
        heading: "3. Acceso gratuito y créditos de pago",
        bullets: [
          { text: "El servicio ofrece 3 lecturas gratuitas por día, renovadas automáticamente cada 24 horas." },
          { text: "Los usuarios pueden adquirir paquetes de créditos adicionales mediante pago a través de Stripe." },
          { text: "Los créditos adquiridos se almacenan localmente en el navegador del usuario. No son reembolsables una vez concedidos." },
          { text: "Los créditos no caducan mientras el usuario conserve los datos de su navegador." },
        ],
      },
      {
        heading: "4. Pagos y facturación",
        body: "Los pagos son procesados por Stripe, Inc. de forma segura. Mystic Tarot no almacena datos de tarjetas de crédito. Los precios mostrados incluyen los impuestos aplicables. En caso de disputa sobre un cargo, el usuario debe contactar con el soporte antes de iniciar un contracargo con su banco.",
      },
      {
        heading: "5. Uso aceptable",
        intro: "El usuario se compromete a no:",
        bullets: [
          { text: "Intentar manipular el sistema de créditos o eludir el sistema de pago." },
          { text: "Usar el servicio para fines ilegales o que puedan causar daño a terceros." },
          { text: "Realizar ingeniería inversa del sistema." },
        ],
      },
      {
        heading: "6. Disponibilidad del servicio",
        body: "Mystic Tarot se ofrece 'tal cual' y no garantiza disponibilidad ininterrumpida. El servicio depende de APIs de terceros (Groq, Stripe, Vercel) cuya disponibilidad está fuera del control del propietario.",
      },
      {
        heading: "7. Limitación de responsabilidad",
        body: "El propietario de Mystic Tarot no será responsable de ningún daño directo, indirecto, incidental o consecuente derivado del uso o la imposibilidad de uso del servicio. Las lecturas generadas son producto de un sistema de inteligencia artificial y no deben tomarse como verdad ni como guía para decisiones importantes.",
      },
      {
        heading: "8. Modificaciones",
        body: "El propietario se reserva el derecho a modificar estos términos en cualquier momento. Los cambios serán efectivos desde su publicación en esta página. El uso continuado del servicio tras dichos cambios implica su aceptación.",
      },
      {
        heading: "9. Ley aplicable",
        body: "Estos términos se rigen por la legislación española y de la Unión Europea. Para cualquier controversia, las partes se someten a los juzgados y tribunales competentes según la normativa aplicable.",
      },
    ],
    footerLinks: [{ label: "Política de Privacidad", href: "/privacy" }, { label: "🔮 Mystic Tarot", href: "/" }],
  },
};

export default function TermsPage() {
  const [lang, setLang] = useState<"EN" | "ES">("EN");

  useEffect(() => {
    const saved = localStorage.getItem("tarotLanguage");
    if (saved === "ES" || saved === "EN") setLang(saved);
  }, []);

  const t = content[lang];

  return (
    <div className="min-h-screen bg-[#0a0a0f] text-slate-200 font-sans px-6 py-16">
      <div className="max-w-2xl mx-auto">
        <div className="flex items-center justify-between mb-10 mt-6">
          <Link href="/" className="text-purple-400 hover:text-purple-300 text-sm inline-flex items-center gap-2 transition-colors">
            <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M19 12H5M12 5l-7 7 7 7"/></svg>
            {t.back}
          </Link>
          <div className="flex gap-1 bg-slate-900 p-1 rounded-lg border border-white/5">
            <button onClick={() => { setLang("EN"); localStorage.setItem("tarotLanguage", "EN"); }} className={`px-3 py-1 rounded text-xs font-bold transition-all ${lang === "EN" ? "bg-purple-700 text-white" : "text-slate-500 hover:text-slate-300"}`}>EN</button>
            <button onClick={() => { setLang("ES"); localStorage.setItem("tarotLanguage", "ES"); }} className={`px-3 py-1 rounded text-xs font-bold transition-all ${lang === "ES" ? "bg-purple-700 text-white" : "text-slate-500 hover:text-slate-300"}`}>ES</button>
          </div>
        </div>

        <h1 className="text-3xl font-bold text-white mb-2">{t.title}</h1>
        <p className="text-slate-500 text-sm mb-10">{t.updated}</p>

        <div className="space-y-8 text-slate-300 leading-relaxed text-sm">
          {t.sections.map((section, i) => (
            <section key={i}>
              <h2 className="text-lg font-semibold text-white mb-3">{section.heading}</h2>
              {section.body && <p className="text-slate-400">{section.body}</p>}
              {section.intro && <p className="text-slate-400 mb-2">{section.intro}</p>}
              {section.bullets && (
                <ul className="list-disc list-inside space-y-2 text-slate-400">
                  {section.bullets.map((b, j) => (
                    <li key={j}>{b.text}</li>
                  ))}
                </ul>
              )}
            </section>
          ))}
        </div>

        <div className="mt-16 pt-8 border-t border-white/5 flex gap-6 text-sm text-slate-500">
          {t.footerLinks.map((l, i) => (
            <Link key={i} href={l.href} className="hover:text-purple-400 transition-colors">{l.label}</Link>
          ))}
        </div>
      </div>
    </div>
  );
}
